project:
  type: book

book:
  title: "Experimental Psyc 2026 Quarto Book"
  author: "Crystal Adote"
  date: "2/19/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - 01-NYC-NYPD-Shooting-data.qmd
    - 02-Continuing_the_Law_Firm_analysis_assignment.qmd
    - 03-Reproducible_psyc_midterm.qmd
    - 04-NBA_analysis.qmd
    - 05-Florida_Crime_Analytics.qmd
    - 06-Streaming_Analysis.qmd
    - 07-Wage_Analytics.qmd
    - 08-shiny-app exploration.qmd
    - 09-Final-Reflection.qmd


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

